[default.extend-words]
ane = "ane"             # Apple Neural Engine
caf = "caf"             # sound file extension
crypted = "crypted"     # LUKS name
edn = "edn"             # Extensible Data Notation
hsa = "hsa"             # health savings account
lod = "lod"             # eza alias
nd = "nd"               # North Dakota
overlayed = "overlayed" # modern Discord voice chat overlay
shortcat = "shortcat"   # macOS app
shotcut = "shotcut"     # video editor
spiritus = "spiritus"   # Latin for spirit
tre = "tre"             # tree command, improved
