# run after login
after-login-command = []

# run after AeroSpace
after-startup-command = []

# start at login
start-at-login = true

# normalizations
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# accordion padding
accordion-padding = 30

# tile by default
default-root-container-layout = "tiles"

# auto orientation
default-root-container-orientation = "auto"

[gaps]
inner.horizontal = 12
inner.vertical = 12
outer.bottom = 50     # bar height (40) + border width (10)
outer.left = 12
outer.right = 12
outer.top = 12

[mode.main.binding]

[workspace-to-monitor-force-assignment]
1 = "main"
2 = "main"
3 = "main"
4 = "main"
5 = "main"
6 = "secondary"
7 = "secondary"
8 = "secondary"
9 = "secondary"
10 = "secondary"

# floaters

[[on-window-detected]]
if.app-id = "com.macpaw.CleanMyMac-setapp"
run = ["layout floating"]
