# NOTEBOOK SETTINGS

[notebook]
dir = "~/Code/github.com/awmckinley/notes"

# NOTE SETTINGS

[note]
default-title = "Untitled"
extension = "md"
filename = "{{id}}"
id-case = "lower"
id-charset = "alphanum"
id-length = 4
language = "en"
template = "default.md"

# EXTRA VARIABLES

[extra]
author = "Adam McKinley"

# GROUP OVERRIDES

[group.journal]
paths = ["journal/weekly", "journal/daily"]

[group.journal.note]
filename = "{{format-date now}}"

# MARKDOWN SETTINGS

[format.markdown]
colon-tags = false
hashtags = true

# EXTERNAL TOOLS

[tool]
editor = "nvim"
fzf-preview = "bat -p --color always {-1}"
pager = "less -FIRX"
shell = "/run/current-system/sw/bin/bash"

# NAMED FILTERS

[filter]
recents = "--sort created- --created-after 'last two weeks'"

# COMMAND ALIASES

[alias]
edlast = "zk edit --limit 1 --sort modified- $@"
recent = "zk edit --sort created- --created-after 'last two weeks' --interactive"

# LSP (EDITOR INTEGRATION)

[lsp]

[lsp.diagnostics]
dead-link = "error"
wiki-title = "hint"
